# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 03:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0002_course_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='password',
            field=models.CharField(default='NULL_NOT_A_PASSWORD', max_length=255),
        ),
    ]
